# generated by datamodel-codegen:
#   filename:  commons.schema.json
#   timestamp: 2025-03-03T19:42:56+00:00

from __future__ import annotations

from typing import Any, List

from pydantic import BaseModel, Field


class Commons(BaseModel):
    __root__: Any = Field(..., description='Commons objects', title='Commons')


class DefaultArray(BaseModel):
    __root__: List = Field(..., max_length=100, min_length=1)
