# generated by datamodel-codegen:
#   filename:  products.json
#   timestamp: 2025-03-03T19:42:54+00:00

from __future__ import annotations

from pydantic import BaseModel, Field

from . import commons


class Products(BaseModel):
    __root__: commons.DefaultArray = Field(
        ..., description='The products in the catalog', title='Products'
    )
